server:
  port: 8761

spring:
  application:
    name: ead-service-registry
  output:
    ansi:
      enabled: ALWAYS

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  server:
    peer-node-read-timeout-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
